version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Adjust if your requirements.txt is in a subfolder
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
